project/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:pk>',views.detail, name='detail')]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls',namespace='app'))
]

project/app/models.py
from django.db import models

# Create your models here.
class TrendRepo(models.Model):

    repo = models.TextField()
    desc = models.TextField()
    star = models.IntegerField()
    detail_desc = models.TextField()
    total_star = models.IntegerField()
    fork = models.IntegerField()
    watch = models.IntegerField()

    def __str__(self):
        return self.repo

project/app/views.py
from django.shortcuts import render
from app.models import TrendRepo
from django.views import generic

# Create your views here.
def index(request):
    trend_list = TrendRepo.objects.all()
    return render(request,'app/index.html',{'trend_list':trend_list})

def detail(request,pk):
    trend = TrendRepo.objects.get(id=pk)
    return render(request,'app/detail.html',{'trend':trend})

project/app/templates/app/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block extra_css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
<nav class="navbar navbar-expand-lg  bg-white fixed-top"> <a class="navbar-brand" href="/">Eureka Summer</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item active"> <a class="nav-link" href="/">TOP</a></li>
        </ul>
    </div>
</nav>
{% block extra_header %}{% endblock %}
</header>

<div class="container">
    {% block content %}
        {{ content }}
    {% endblock %}
</div>

<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% block extra_js %}{% endblock %}
</body>
</html>

project/app/templates/app/detail.html
{% extends "app/base.html" %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/detailpage_style.css' %}" />
{% endblock %}
{% block title %}DetailPage : {{ trend.repo }}{% endblock %}
{% block content %}
    <h3>repository name</h3>
    <h2>
        <img src="{% static 'app/img/book.png' %}" height="28"/> <a href="https://github.com/{{ trend.repo }}">{{ trend.repo }}</a>
    </h2>
<ul class="pagehead-actions">
<li class="social-count watch">
<span>Watch <img src="{% static 'app/img/eye.png' %}" height="28"/> : </span>{{ trend.watch }}
</li>
<li class="social-count total_star">
<span>Star <img src="{% static 'app/img/star.png' %}" height="28"/> : </span>{{ trend.total_star }}
</li>
<li class="social-count fork">
<span>Fork <img src="{% static 'app/img/fork.png' %}" height="28"/> : </span>{{ trend.fork }}
</li>
</ul>
<h3>README.md</h3>
<div class="detail_desc rounded">
    <pre>{{ trend.detail_desc }}</pre>
</div>
{% endblock %}

project/app/templates/app/index.html
{% extends "app/base.html" %}
{% load static %}
{% block extra_header %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1>To create a world<br>where everyone can maximize their<br>life's potential.</h1>
    </div>
</div>
{% endblock %}
{% block title %}Index Page{% endblock %}
{% block content %}
    <h2>Github Trend</h2>
<div class="trend-list">
{% for trend in trend_list %}
    <div class="trend-repo rounded">
        <a href="{% url 'app:detail' trend.pk %}" title="{{ trend.desc }}">{{ trend.repo }}<span>{{ trend.star }} stars today</span></a>
    </div>
{% endfor %}
</div>
{% endblock %}
{% block extra_js %}<script src="{% static 'app/js/index.js' %}"></script>{% endblock %}