github_trend/config/routes.rb
Rails.application.routes.draw do
  resources :repositories, only: %i(index show)

  root to: 'repositories#index'
  get 'repos/:period' => 'repositories#index'
end

github_trend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

github_trend/app/models/month_trend_repositorie.rb
class MonthTrendRepositorie < Repositorie
end

github_trend/app/models/repositorie.rb
class Repositorie < ApplicationRecord
  validates :name, presence: true
  validates :type, presence: true
  validates :name, length: { maximum: 25 }
  validates :discription, length: { maximum: 255 }

  after_create :fetch_detail_data

  def fetch_detail_data
    html = open("https://github.com/#{name}")

    doc = Nokogiri::HTML.parse(html)
    readme = doc.css("#readme").to_s

    update!(readme: readme)
  end
end

github_trend/app/models/today_trend_repositorie.rb
class TodayTrendRepositorie < Repositorie
end

github_trend/app/models/week_trend_repositorie.rb
class WeekTrendRepositorie < Repositorie
end

github_trend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

github_trend/app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def index
    case params[:period]
    when 'weekly'
      @repos = WeekTrendRepositorie.all
    when 'month'
      @repos = MonthTrendRepositorie.all
    else
      @repos = TodayTrendRepositorie.all
    end
  end

  def show
    @repo = Repositorie.find(params[:id])
  end
end

github_trend/app/helpers/application_helper.rb
module ApplicationHelper
end

github_trend/app/views/repositories/index.html.slim
= render 'shared/header'

ul.collection
  - @repos.each do |repo|
    li.collection-header
      = link_to repo.name, repository_path(repo)
    li.collection-item
      = repo.discription

github_trend/app/views/repositories/show.html.slim
h1
  = @repo.name

= raw @repo.readme

github_trend/app/views/shared/_header.html.slim
nav
  .nav-wrapper
    = link_to 'GitHubTrend', root_path, class: 'brand-logo'
    ul.hide-on-med-and-down.right
      li
        = link_to 'today', '/repos/today'
      li
        = link_to 'weekly', '/repos/weekly'
      li
        = link_to 'month', '/repos/month'