git-trand/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  resources :toppages, only: [:index, :show]
end

git-trand/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

git-trand/app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
require 'nokogiri'
require 'open-uri'
  def index
    get_trends
    
  end

  def show
    get_trends
    @content = @contents[params[:id]]
    
  end
  
  private
  def get_trends
    url = 'https://github.com/trending'
    
    charset = nil
    html = open(url) do |f|
      charset = f.charset 
      f.read 
    end
    
    
    doc = Nokogiri::HTML.parse(html, nil, charset)
    @titles = []
    @contents = {}
    doc.xpath('//li[@class="col-12 d-block width-full py-4 border-bottom"]').each do |node|
       title =  node.xpath('.//h3/a/@href')[0].text
       title.slice!(0)
       @titles.push(title)
       
    
       
       content = node.xpath('.//p[@class="col-9 d-inline-block text-gray m-0 pr-4"]').text
       content.slice!("\n")
       content.strip!
       @contents[title] = content
      
    end
  end
end

git-trand/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
      <div class="navbar-header">
        <a href="#" class="navbar-brand">GitTrends</a>
      </div>
</nav>

git-trand/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>GitTrends</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>


  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

git-trand/app/views/toppages/index.html.erb
<div class="title">
    <% @titles.each do |title| %>
      <div class="text-center">
        <%= link_to title, toppage_path(title) %>
      </div>
     
    <% end %>

</div>

git-trand/app/views/toppages/show.html.erb
<div class="content text-center">
  <h1>Content</h1>
  <p><%= @content %></p>
</div>